services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    env_file:
      - .env
    ports:
      - '8080:8000'
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./user-service:/var/www/html:cached

  enrichment-service:
    build: ./enrichment-service
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3001:3000'
    volumes:
      - ./enrichment-service:/usr/src/app:cached

  frontend:
    build: ./frontend
    depends_on:
      - user-service
      - enrichment-service
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_ENRICHMENT_API_URL=http://localhost:3001

volumes:
  mysql_data:
  mongo_data: 